# Generated by Django 2.1.4 on 2018-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181228_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hot_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
