# Generated by Django 2.1.4 on 2019-01-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexpagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSearchPage',
            fields=[
                ('blogindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogIndexPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogindexpage',),
        ),
    ]
